#!/usr/bin/env perl
use Dzpl
    name => 'YUI-Loader',
    version => '0.071',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',

    require => q/
        Algorithm::Dependency
        Carp::Clan::Share
        File::Copy
        HTML::Declare
        JSON 2.08
        LWP::UserAgent
        Moose
        Path::Abstract
        Path::Class
        Scalar::Util
        URI

        [Test]
        Test::Most
        Directory::Scratch
    /,
;

{ plugin '@ROKR' }

